// Test migration

INSERT INTO author (created_at, updated_at, name, description)
VALUES (current_timestamp, current_timestamp, 'Luiz Yamaoka', 'A comissão norte-coreana também acusou Washington de, "sem fundamentos", responsabilizar a Coreia do Norte pelo ataque virtual à Sony. Inicialmente, a Sony Pictures havia cancelado a estreia do filme, após sofrer um ataque cibernético sem precedentes de um grupo que se autodenomina Guardiães da Paz. Os hackers que invadiram a Sony também ameaçaram atacar cinemas que exibissem o filme.');

INSERT INTO article (created_at, updated_at, title, subtitle, content, author_id)
VALUES (current_timestamp, current_timestamp, 'O que é BTU?', 'Saiba como escolher seu ar condicionado', '<p>Lorem ipsum dolor sit amet, <strong>consectetur adipiscing</strong> elit, sed do eiusmod tempor incididunt ut <a href="http://www.google.com.br">labore</a> et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p> 	Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>', 1),
(current_timestamp, current_timestamp, 'Artigo teste', 'Subtitulo pequeno', '<p>Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt, explicabo. Nemo enim ipsam voluptatem, quia voluptas sit, aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos, qui ratione voluptatem sequi nesciunt, neque porro quisquam est, qui dolorem ipsum, quia dolor sit amet consectetur adipisci[ng] velit, sed quia non numquam [do] eius modi tempora inci[di]dunt, ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit, qui in ea voluptate velit esse, quam nihil molestiae consequatur, vel illum, qui dolorem eum fugiat, quo voluptas nulla pariatur?</p>', 1),
(current_timestamp, current_timestamp, 'Titulo comprido para ver o qeu acontece com o layout, sera que ele quebra? teste teste teste', 'Subtitulo pequeno', '<p>But I must explain to you how all this mistaken idea of denouncing of a pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?</p>', 1),
(current_timestamp, current_timestamp, 'Artigo teste', 'Subtitulo grande apra ver o que acontece com o laupit skjda lkj siad ad mkaljd jaskj', '<p>At vero eos et accusamus et iusto odio dignissimos ducimus, qui blanditiis praesentium voluptatum deleniti atque corrupti, quos dolores et quas molestias excepturi sint, obcaecati cupiditate non provident, similique sunt in culpa, qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio, cumque nihil impedit, quo minus id, quod maxime placeat, facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet, ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat… At vero eos et accusamus et iusto odio dignissimos ducimus, qui blanditiis praesentium voluptatum deleniti atque corrupti, quos dolores et quas molestias excepturi sint, obcaecati cupiditate non provident, similique sunt in culpa, qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio, cumque nihil impedit, quo minus id, quod maxime placeat, facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet, ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat…</p>', 1),
(current_timestamp, current_timestamp, 'Titulo comprido para ver o qeu acontece com o layout, sera que ele quebra? teste teste tes', 'Subtitulo grande apra ver o que acontece com o laupit skjda lkj siad ad mkaljd jaskj', '<p>On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammeled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains.</p>', 1),
(current_timestamp, current_timestamp, 'Coreia do Norte acusou o presidente dos Estados Unidos', 'A decisão de cancelar o lançamento foi fortemente criticada', '<p>Em comunicado divulgado no sábado (26), o porta-voz da Comissão de Defesa Nacional norte-coreana criticou fortemente os EUA pelo "filme desonesto e reacionário que fere a dignidade da liderança suprema da Coreia do Norte e provoca terrorismo". Segundo o documento, Obama é "o principal culpado que forçou a Sony Pictures Entertainment a distribuir indiscriminadamente o filme", chantageando cinemas nos EUA.</p><p>A grande dificuldade de Kim Jong-un é que "A Entrevista" - que apresenta o líder norte-coreano como um bobo maligna e vão - tem sido amplamente visto como engraçado e perspicaz, disse o correspondente da BBC em Seul, Stephen Evans. Se ativistas contrabandearem o filme para a Coreia do Norte em pen-drives, como já fazem com outros filmes, o longa poderá revelar-se bastante poderoso, disse Evans.</p>', 1);

INSERT INTO article_is_type (created_at, article_id, article_type_id)
VALUES (current_timestamp, 7, 1),
(current_timestamp, 8, 1),
(current_timestamp, 9, 1),
(current_timestamp, 12, 1);

INSERT INTO article_is_sport (created_at, article_id, sport_id)
VALUES (current_timestamp, 7, 1),
(current_timestamp, 10, 1),
(current_timestamp, 11, 1);

INSERT INTO uri (created_at, updated_at, uri, friendly_uri, name, parent_id)
VALUES (current_timestamp, current_timestamp, '/authors/1', '/luiz-yamaoka', 'Luiz Yamaoka', 5);