/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2015-01-25 03:34:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.shared;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class css_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- jQuery -->\n");
      out.write("<link rel=\"stylesheet\" href=\"//ajax.googleapis.com/ajax/libs/jqueryui/1.11.0/themes/smoothness/jquery-ui.css\" />\n");
      out.write("\n");
      out.write("<!-- Latest compiled and minified CSS -->\n");
      out.write("<link rel=\"stylesheet\" href=\"//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css\">\n");
      out.write("\n");
      out.write("<!-- Optional theme -->\n");
      out.write("<link rel=\"stylesheet\" href=\"//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css\">\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("/* Space out content a bit */\n");
      out.write("body {\n");
      out.write("  padding-top: 20px;\n");
      out.write("  padding-bottom: 20px;\n");
      out.write("}\n");
      out.write(".header {\n");
      out.write("  padding-right: 15px;\n");
      out.write("  padding-left: 15px;\n");
      out.write("  margin-bottom: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#logo {\n");
      out.write("  line-height: 40px;\n");
      out.write("  margin-bottom: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav-pills > li > a {\n");
      out.write("    font-size: 14px;\n");
      out.write("    color: #4d4d4d;\n");
      out.write("    border: 1px solid #fff;\n");
      out.write("    border-radius: 5px 5px 5px 5px;\n");
      out.write("    padding: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav-pills > li > a:hover {\n");
      out.write("    background-color: #fff;\n");
      out.write("    color: #ff6600;\n");
      out.write("    border: 1px solid #ff6600;\n");
      out.write("}\n");
      out.write(".nav-pills > li > a:focus {\n");
      out.write("    background-color: #fff;\n");
      out.write("    color: #ff6600;\n");
      out.write("    border: 1px solid #ff6600;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".icon-bar {\n");
      out.write("  display: block;\n");
      out.write("  width: 22px;\n");
      out.write("  height: 2px;\n");
      out.write("  background-color: #4d4d4d;\n");
      out.write("  border-radius: 1px;\n");
      out.write("  margin-bottom: 3px;\n");
      out.write("}\n");
      out.write(".alert {\n");
      out.write("  margin: 10px 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".btn-big {\n");
      out.write("  font-size: 16px;\n");
      out.write("  color: #ff6600;\n");
      out.write("  font-weight: bold;\n");
      out.write("  border: 1px solid #ff6600;\n");
      out.write("  border-radius: 5px 5px 5px 5px;\n");
      out.write("  padding: 15px 40px 15px 40px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".btn-big:hover{\n");
      out.write("  font-size: 16px;\n");
      out.write("  color: #fff;\n");
      out.write("  font-weight: bold;\n");
      out.write("  background-color: #ff6600;\n");
      out.write("  text-decoration: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".btn-medium {\n");
      out.write("  font-size: 14px;\n");
      out.write("  color: #ff6600;\n");
      out.write("  font-weight: bold;\n");
      out.write("  border: 1px solid #ff6600;\n");
      out.write("  border-radius: 5px 5px 5px 5px;\n");
      out.write("  padding: 10px 30px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".btn-medium:hover{\n");
      out.write("  font-size: 14px;\n");
      out.write("  color: #fff;\n");
      out.write("  font-weight: bold;\n");
      out.write("  background-color: #ff6600;\n");
      out.write("  text-decoration: none;\n");
      out.write("}\n");
      out.write(".thumbnail {\n");
      out.write("  padding-bottom: 30px;\n");
      out.write("  height: 400px;\n");
      out.write("}\n");
      out.write(".thumbnail > .caption {\n");
      out.write("  overflow: hidden;\n");
      out.write("  height: 300px;\n");
      out.write("  margin-bottom: 30px;\n");
      out.write("}\n");
      out.write(".thumbnail > .caption > h4 {\n");
      out.write("  height: 80px;\n");
      out.write("}\n");
      out.write(".thumbnail > .caption > .author-name {\n");
      out.write("  height: 40px;\n");
      out.write("}\n");
      out.write(".thumbnail > .caption > .article-beginning {\n");
      out.write("  text-align: justify;\n");
      out.write("  margin: 40px 0px;\n");
      out.write("  overflow: hidden;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".jumbotron {\n");
      out.write("  padding-bottom: 70px;  \n");
      out.write("}\n");
      out.write(".center-form {\n");
      out.write("  max-width: 600px;\n");
      out.write("  margin: 0 auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write("// Artigos\n");
      out.write("\n");
      out.write(".article > h3 {\n");
      out.write("  color: #777777;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".article > .author {\n");
      out.write("  font-size: 14px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".article > .content {\n");
      out.write("  font-size: 16px;\n");
      out.write("  line-height: 2em;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".article > .content > p > strong {\n");
      out.write("  color: #ff6600;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".article > .content > p {\n");
      out.write("  margin-bottom: 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".article > .secondary-text {\n");
      out.write("  color: #999999;\n");
      out.write("  font-size: 16px;\n");
      out.write("  line-height: 2em;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".comment {\n");
      out.write("  font-size: 16px;\n");
      out.write("  border-radius: 5px 5px 5px 5px;\n");
      out.write("  background-color: #eeeeee;\n");
      out.write("  padding: 20px;\n");
      out.write("  margin: 10px 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".breadcrumb {\n");
      out.write("  background-color: #fff;\n");
      out.write("  margin-bottom: 10px;\n");
      out.write("}\n");
      out.write(".list-group > a:hover {\n");
      out.write("  background-color: #ff6600;\n");
      out.write("  color: #fff;\n");
      out.write("}\n");
      out.write(".list-group > a:focus {\n");
      out.write("  background-color: #ff6600;\n");
      out.write("  color: #fff;\n");
      out.write("}\n");
      out.write(".list-group > div > a:hover {\n");
      out.write("  background-color: #ff6600;\n");
      out.write("  color: #fff;\n");
      out.write("}\n");
      out.write(".read-more {\n");
      out.write("  font-size: 14px;\n");
      out.write("  padding: 20px 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".comment > .client {\n");
      out.write("  font-size: 14px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("// Client show page\n");
      out.write("\n");
      out.write(".container > .center-form > .form-group > .client-field-name {\n");
      out.write("  text-align: right;\n");
      out.write("  color: #ff0000;\n");
      out.write("}\n");
      out.write("@media screen and (max-width: 768px){\n");
      out.write("  .container > .center-form > .form-group > .client-field-name {\n");
      out.write("    text-align: left; \n");
      out.write("  }\n");
      out.write("}\n");
      out.write("\n");
      out.write(".carousel-caption > p {\n");
      out.write("  font-size: 21px;\n");
      out.write("  line-height: 1.4;\n");
      out.write("}\n");
      out.write("#main-menu {\n");
      out.write("  \tbackground-color: #ff6600;\n");
      out.write("  \theight: 30px;\n");
      out.write("  \tmargin-bottom: 5px;\n");
      out.write("  }\n");
      out.write("#main-menu > .container > a {\n");
      out.write("\tline-height: 30px;\n");
      out.write("\tfont-size: 15px;\n");
      out.write("\tcolor: #ffffff;\n");
      out.write("\tmargin: 0 10px;\n");
      out.write("\tfont-weight: bold;\n");
      out.write("}\n");
      out.write("#main-menu > .container > a:hover {\n");
      out.write("\ttext-decoration: none;\n");
      out.write("\tcolor: #4d4d4d;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#about-us {\n");
      out.write("  text-align: center;\n");
      out.write("}\n");
      out.write("#about-us > .row {\n");
      out.write("  margin-bottom: 20px;\n");
      out.write("}\n");
      out.write("#about-us > h3 {\n");
      out.write("  margin-bottom: 20px;\n");
      out.write("}\n");
      out.write("#about-us > p {\n");
      out.write("  font-size: 16px;\n");
      out.write("  line-height: 2em;\n");
      out.write("  text-align: left;\n");
      out.write("}\n");
      out.write("#about-us > p > strong {\n");
      out.write("  color: #ff6600;\n");
      out.write("}\n");
      out.write("#footer-box {\n");
      out.write("  margin-top: 20px;\n");
      out.write("  border-top: 1px solid #eee;\n");
      out.write("  padding-top: 20px;\n");
      out.write("}\n");
      out.write("#footer-box > .row > div > h4 {\n");
      out.write("  padding-left: 40px;\n");
      out.write("}\n");
      out.write("#footer-box > .row > div > ul {\n");
      out.write("  list-style-type: none;\n");
      out.write("}\n");
      out.write("#footer-social {\n");
      out.write("  float: left;\n");
      out.write("}\n");
      out.write("#footer-social > li {\n");
      out.write("  float: left;\n");
      out.write("  margin: 0 6px;\n");
      out.write("}\n");
      out.write("#footer-social > li > a {\n");
      out.write("  float: left;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
