/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2015-01-25 03:34:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.shared;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<div class=\"footer\">\n");
      out.write("  <div class=\"container\" id=\"footer-box\">\n");
      out.write("    <div class=\"row\">\n");
      out.write("      <div class=\"col-sm-6 col-xs-12\">\n");
      out.write("        <h4>A Sportaholic</h4>\n");
      out.write("        <ul>\n");
      out.write("          <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${uriService.getFriendlyUri('/about-us')}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">Quem somos</a></li>\n");
      out.write("          <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${uriService.getFriendlyUri('/contact-us')}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">Contato</a></li>\n");
      out.write("        </ul>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"col-sm-6 col-xs-12\">\n");
      out.write("        <h4>#sportaholic <small>get social</small></h4>\n");
      out.write("        <ul id=\"footer-social\">\n");
      out.write("          <li><a href=\"http://www.facebook.com.br/sportaholicoficial\" target=\"blank\"><img src=\"https://s3-sa-east-1.amazonaws.com/sportaholic/images/facebook.png\" height=\"29px\" width=\"29px\" alt=\"facebook\" /></a></li>\n");
      out.write("          <li><a href=\"http://plus.google.com/+SportaholicBrasil\" target=\"blank\"><img src=\"https://s3-sa-east-1.amazonaws.com/sportaholic/images/gplus.png\" height=\"29px\" width=\"29px\" alt=\"google plus\" /></a></li>\n");
      out.write("          <li><a href=\"http://twitter.com/sportaholicBr\" target=\"blank\"><img src=\"https://s3-sa-east-1.amazonaws.com/sportaholic/images/twitter.png\" height=\"29px\" width=\"29px\" alt=\"twitter\" /></a></li>\n");
      out.write("          <li><a href=\"http://instagram.com/sportaholicoficial\" target=\"blank\"><img src=\"https://s3-sa-east-1.amazonaws.com/sportaholic/images/instagram.png\" height=\"29px\" width=\"29px\" alt=\"instagram\" /></a></li>\n");
      out.write("          <li><a href=\"http://www.youtube.com/channel/UCfRO7VrKyT8ZBSdm6AiHqew\" target=\"blank\"><img src=\"https://s3-sa-east-1.amazonaws.com/sportaholic/images/youtube.png\" height=\"29px\" width=\"29px\" alt=\"youtube\" /></a></li>\n");
      out.write("        </ul>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  <hr />\n");
      out.write("  <div class=\"container\">\n");
      out.write("    <p style=\"text-align: center;\">\n");
      out.write("      2014, Sportaholic\n");
      out.write("    </p>\n");
      out.write("  </div>\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
