ALTER TABLE sport
ADD COLUMN banner text NOT NULL DEFAULT '';

ALTER TABLE sport
ALTER COLUMN banner DROP DEFAULT;

ALTER TABLE sport
ADD COLUMN description text NOT NULL DEFAULT '';

ALTER TABLE sport
ALTER COLUMN description DROP DEFAULT;
